// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVxUOEiOC5WvlRZiGJ7Qarm_pfFSJpOZ0',
    appId: '1:479407077856:web:405a36d107ec1e7e225385',
    messagingSenderId: '479407077856',
    projectId: 'hawia-11d8f',
    authDomain: 'hawia-11d8f.firebaseapp.com',
    storageBucket: 'hawia-11d8f.firebasestorage.app',
    measurementId: 'G-HR3JNW5MRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiwYixw0E06-2xnV1QfaI8QOoKcXHc348',
    appId: '1:479407077856:android:840e35d0a0d29f0a225385',
    messagingSenderId: '479407077856',
    projectId: 'hawia-11d8f',
    storageBucket: 'hawia-11d8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB05P0nu5ukRxjgXFhqt8W1ZWZpGxqeJqM',
    appId: '1:479407077856:ios:35c2470d24dcdccd225385',
    messagingSenderId: '479407077856',
    projectId: 'hawia-11d8f',
    storageBucket: 'hawia-11d8f.firebasestorage.app',
    iosBundleId: 'com.future.hawyaDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB05P0nu5ukRxjgXFhqt8W1ZWZpGxqeJqM',
    appId: '1:479407077856:ios:35c2470d24dcdccd225385',
    messagingSenderId: '479407077856',
    projectId: 'hawia-11d8f',
    storageBucket: 'hawia-11d8f.firebasestorage.app',
    iosBundleId: 'com.future.hawyaDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVxUOEiOC5WvlRZiGJ7Qarm_pfFSJpOZ0',
    appId: '1:479407077856:web:645dcbfd01410656225385',
    messagingSenderId: '479407077856',
    projectId: 'hawia-11d8f',
    authDomain: 'hawia-11d8f.firebaseapp.com',
    storageBucket: 'hawia-11d8f.firebasestorage.app',
    measurementId: 'G-SQT1VG2CYS',
  );
}
